"""Deterministic local seed records."""

from __future__ import annotations

from datetime import UTC, datetime
import re
from uuid import NAMESPACE_URL, uuid5

LOCAL_USER = {
    "id": "11111111-1111-1111-1111-111111111111",
    "seed_key": "local_user",
    "display_name": "Local User",
    "email": None,
}

_REGION_LABELS = {
    "quebec": "Quebec, Canada",
    "canada": "Canada",
    "us": "United States",
    "dubai": "Dubai, UAE",
}
_ACTIVE_SOURCE_TYPES = {"applytojob", "ashby", "greenhouse", "lever", "manual", "smartrecruiters", "workday"}
_NON_ALNUM_PATTERN = re.compile(r"[^a-z0-9]+")
_MULTI_DASH_PATTERN = re.compile(r"-{2,}")


def _seed_uuid(kind: str, slug: str, qualifier: str = "") -> str:
    return str(uuid5(NAMESPACE_URL, f"job-discovery:{kind}:{slug}:{qualifier}"))


def _slugify(value: str) -> str:
    normalized = _NON_ALNUM_PATTERN.sub("-", value.lower()).strip("-")
    return _MULTI_DASH_PATTERN.sub("-", normalized)


def _default_base_url(source_type: str, external_key: str, website_url: str | None) -> str | None:
    if source_type == "applytojob":
        return f"https://{external_key}.applytojob.com/apply"
    if source_type == "ashby":
        return f"https://jobs.ashbyhq.com/{external_key}"
    if source_type == "greenhouse":
        return f"https://boards.greenhouse.io/{external_key}"
    if source_type == "lever":
        return f"https://jobs.lever.co/{external_key}"
    return website_url


def _build_seed_record(
    *,
    region: str,
    name: str,
    slug: str | None = None,
    source_type: str = "manual",
    external_key: str | None = None,
    website_url: str | None = None,
    base_url: str | None = None,
    configuration: dict | None = None,
) -> dict:
    company_slug = slug or _slugify(name)
    source_key = external_key or company_slug
    is_active = source_type in _ACTIVE_SOURCE_TYPES
    lifecycle_status = "active" if is_active else "paused"
    resolved_base_url = base_url or _default_base_url(source_type, source_key, website_url)
    sync_tier = (
        "sync-ready"
        if source_type in {"applytojob", "ashby", "greenhouse", "lever", "smartrecruiters", "workday"}
        else "operator-managed"
    )
    return {
        "company": {
            "id": _seed_uuid("company", company_slug),
            "slug": company_slug,
            "name": name,
            "website_url": website_url,
            "description": f"Seeded {sync_tier} company for { _REGION_LABELS[region] }.",
            "lifecycle_status": lifecycle_status,
        },
        "source": {
            "id": _seed_uuid("source", company_slug, source_type),
            "source_type": source_type,
            "external_key": source_key,
            "base_url": resolved_base_url,
            "configuration": {
                "seed_region": region,
                "seed_region_label": _REGION_LABELS[region],
                "seed_sync_tier": sync_tier,
                **(configuration or {}),
            },
            "is_enabled": is_active,
        },
    }


def _supported_companies() -> tuple[dict, ...]:
    specs = (
        {"region": "us", "name": "OpenAI", "source_type": "ashby", "external_key": "openai", "website_url": "https://openai.com"},
        {"region": "us", "name": "Notion", "source_type": "ashby", "external_key": "notion", "website_url": "https://www.notion.so"},
        {"region": "us", "name": "Ramp", "source_type": "ashby", "external_key": "ramp", "website_url": "https://ramp.com"},
        {"region": "us", "name": "Vanta", "source_type": "ashby", "external_key": "vanta", "website_url": "https://www.vanta.com"},
        {"region": "us", "name": "Linear", "source_type": "ashby", "external_key": "linear", "website_url": "https://linear.app"},
        {
            "region": "us",
            "name": "Perplexity",
            "source_type": "ashby",
            "external_key": "perplexity",
            "website_url": "https://www.perplexity.ai",
        },
        {"region": "us", "name": "Mercor", "source_type": "ashby", "external_key": "mercor", "website_url": "https://mercor.com"},
        {"region": "us", "name": "Warp", "source_type": "ashby", "external_key": "warp", "website_url": "https://www.warp.dev"},
        {"region": "us", "name": "Harvey", "source_type": "ashby", "external_key": "harvey", "website_url": "https://www.harvey.ai"},
        {"region": "us", "name": "Runway", "source_type": "ashby", "external_key": "runway", "website_url": "https://runwayml.com"},
        {"region": "us", "name": "Sierra", "source_type": "ashby", "external_key": "sierra", "website_url": "https://sierra.ai"},
        {"region": "us", "name": "Render", "source_type": "ashby", "external_key": "render", "website_url": "https://render.com"},
        {"region": "us", "name": "Replit", "source_type": "ashby", "external_key": "replit", "website_url": "https://replit.com"},
        {"region": "us", "name": "Vercel", "source_type": "greenhouse", "external_key": "vercel", "website_url": "https://vercel.com"},
        {"region": "us", "name": "Stripe", "source_type": "greenhouse", "external_key": "stripe", "website_url": "https://stripe.com"},
        {"region": "us", "name": "Plaid", "source_type": "lever", "external_key": "plaid", "website_url": "https://plaid.com"},
        {"region": "us", "name": "Figma", "source_type": "greenhouse", "external_key": "figma", "website_url": "https://www.figma.com"},
        {
            "region": "us",
            "name": "Datadog",
            "source_type": "greenhouse",
            "external_key": "datadog",
            "website_url": "https://www.datadoghq.com",
        },
        {"region": "us", "name": "Airbnb", "source_type": "greenhouse", "external_key": "airbnb", "website_url": "https://www.airbnb.com"},
        {"region": "us", "name": "Reddit", "source_type": "greenhouse", "external_key": "reddit", "website_url": "https://www.reddit.com"},
        {
            "region": "us",
            "name": "Coinbase",
            "source_type": "greenhouse",
            "external_key": "coinbase",
            "website_url": "https://www.coinbase.com",
        },
        {
            "region": "us",
            "name": "Instacart",
            "source_type": "greenhouse",
            "external_key": "instacart",
            "website_url": "https://www.instacart.com",
        },
        {
            "region": "us",
            "name": "Robinhood",
            "source_type": "greenhouse",
            "external_key": "robinhood",
            "website_url": "https://robinhood.com",
        },
        {"region": "us", "name": "Discord", "source_type": "greenhouse", "external_key": "discord", "website_url": "https://discord.com"},
        {
            "region": "us",
            "name": "Flexport",
            "source_type": "greenhouse",
            "external_key": "flexport",
            "website_url": "https://www.flexport.com",
        },
        {"region": "us", "name": "Brex", "source_type": "greenhouse", "external_key": "brex", "website_url": "https://www.brex.com"},
        {
            "region": "us",
            "name": "Coursera",
            "source_type": "greenhouse",
            "external_key": "coursera",
            "website_url": "https://www.coursera.org",
        },
        {"region": "us", "name": "Asana", "source_type": "greenhouse", "external_key": "asana", "website_url": "https://asana.com"},
        {
            "region": "us",
            "name": "Dropbox",
            "source_type": "greenhouse",
            "external_key": "dropbox",
            "website_url": "https://www.dropbox.com",
        },
        {"region": "us", "name": "Affirm", "source_type": "greenhouse", "external_key": "affirm", "website_url": "https://www.affirm.com"},
        {
            "region": "us",
            "name": "Calendly",
            "source_type": "greenhouse",
            "external_key": "calendly",
            "website_url": "https://calendly.com",
        },
        {"region": "us", "name": "Lyft", "source_type": "greenhouse", "external_key": "lyft", "website_url": "https://www.lyft.com"},
        {
            "region": "us",
            "name": "Doximity",
            "source_type": "greenhouse",
            "external_key": "doximity",
            "website_url": "https://www.doximity.com",
        },
        {
            "region": "us",
            "name": "Rockwell Automation",
            "source_type": "workday",
            "external_key": "rockwellautomation",
            "website_url": "https://www.rockwellautomation.com",
            "base_url": "https://rockwellautomation.wd1.myworkdayjobs.com/en-US/External_Rockwell_Automation",
        },
        {
            "region": "quebec",
            "name": "Lightspeed",
            "source_type": "greenhouse",
            "external_key": "lightspeedhq",
            "website_url": "https://www.lightspeedhq.com",
        },
        {
            "region": "quebec",
            "name": "AppDirect",
            "source_type": "greenhouse",
            "external_key": "appdirect",
            "website_url": "https://www.appdirect.com",
        },
        {
            "region": "quebec",
            "name": "Hopper",
            "source_type": "ashby",
            "external_key": "hopper",
            "website_url": "https://hopper.com",
        },
        {
            "region": "quebec",
            "name": "MaintainX",
            "source_type": "greenhouse",
            "external_key": "maintainx",
            "website_url": "https://www.getmaintainx.com",
        },
        {
            "region": "quebec",
            "name": "Plusgrade",
            "source_type": "lever",
            "external_key": "plusgrade",
            "website_url": "https://www.plusgrade.com",
        },
        {
            "region": "quebec",
            "name": "Plotly",
            "source_type": "greenhouse",
            "external_key": "plotly",
            "website_url": "https://plotly.com",
        },
        {
            "region": "quebec",
            "name": "Vooban",
            "source_type": "greenhouse",
            "external_key": "vooban",
            "website_url": "https://www.vooban.com",
        },
        {
            "region": "quebec",
            "name": "Workleap",
            "source_type": "greenhouse",
            "external_key": "workleap",
            "website_url": "https://workleap.com",
        },
        {
            "region": "quebec",
            "name": "Deep Sky",
            "source_type": "lever",
            "external_key": "deepsky",
            "website_url": "https://deepskyclimate.com",
        },
        {
            "region": "quebec",
            "name": "Vention",
            "source_type": "smartrecruiters",
            "external_key": "vention",
            "website_url": "https://vention.io",
        },
        {
            "region": "canada",
            "name": "Wealthsimple",
            "source_type": "lever",
            "external_key": "wealthsimple",
            "website_url": "https://www.wealthsimple.com",
        },
        {
            "region": "canada",
            "name": "1Password",
            "source_type": "ashby",
            "external_key": "1password",
            "website_url": "https://1password.com",
        },
        {
            "region": "canada",
            "name": "BenchSci",
            "source_type": "lever",
            "external_key": "benchsci",
            "website_url": "https://www.benchsci.com",
        },
        {
            "region": "canada",
            "name": "Benevity",
            "source_type": "greenhouse",
            "external_key": "benevity",
            "website_url": "https://benevity.com",
        },
        {
            "region": "canada",
            "name": "Clearco",
            "source_type": "ashby",
            "external_key": "clearco",
            "website_url": "https://clear.co",
        },
        {
            "region": "canada",
            "name": "ecobee",
            "source_type": "greenhouse",
            "external_key": "ecobee",
            "website_url": "https://www.ecobee.com",
        },
        {
            "region": "canada",
            "name": "Float",
            "source_type": "ashby",
            "external_key": "float",
            "website_url": "https://floatcard.com",
        },
        {
            "region": "canada",
            "name": "Geotab",
            "source_type": "greenhouse",
            "external_key": "geotab",
            "website_url": "https://www.geotab.com",
        },
        {
            "region": "canada",
            "name": "Jane App",
            "source_type": "lever",
            "external_key": "janeapp",
            "website_url": "https://jane.app",
        },
        {
            "region": "canada",
            "name": "Jobber",
            "source_type": "ashby",
            "external_key": "jobber",
            "website_url": "https://getjobber.com",
        },
        {
            "region": "canada",
            "name": "KOHO",
            "source_type": "ashby",
            "external_key": "koho",
            "website_url": "https://www.koho.ca",
        },
        {
            "region": "canada",
            "name": "Magnet Forensics",
            "source_type": "lever",
            "external_key": "magnetforensics",
            "website_url": "https://www.magnetforensics.com",
        },
        {
            "region": "canada",
            "name": "Neo Financial",
            "source_type": "ashby",
            "external_key": "neofinancial",
            "website_url": "https://www.neofinancial.com",
        },
        {
            "region": "canada",
            "name": "PointClickCare",
            "source_type": "lever",
            "external_key": "pointclickcare",
            "website_url": "https://pointclickcare.com",
        },
        {
            "region": "canada",
            "name": "StackAdapt",
            "source_type": "greenhouse",
            "external_key": "stackadapt",
            "website_url": "https://www.stackadapt.com",
        },
        {
            "region": "canada",
            "name": "Thinkific",
            "source_type": "greenhouse",
            "external_key": "thinkific",
            "website_url": "https://www.thinkific.com",
        },
        {
            "region": "canada",
            "name": "TouchBistro",
            "source_type": "greenhouse",
            "external_key": "touchbistro",
            "website_url": "https://www.touchbistro.com",
        },
        {
            "region": "canada",
            "name": "Unbounce",
            "source_type": "greenhouse",
            "external_key": "unbounce",
            "website_url": "https://unbounce.com",
        },
        {
            "region": "canada",
            "name": "Wattpad",
            "source_type": "lever",
            "external_key": "wattpad",
            "website_url": "https://www.wattpad.com",
        },
        {
            "region": "canada",
            "name": "Hootsuite",
            "source_type": "smartrecruiters",
            "external_key": "hootsuite",
            "website_url": "https://www.hootsuite.com",
        },
        {
            "region": "dubai",
            "name": "Careem",
            "source_type": "greenhouse",
            "external_key": "careem",
            "website_url": "https://www.careem.com",
        },
        {
            "region": "us",
            "name": "Palantir",
            "source_type": "smartrecruiters",
            "external_key": "palantir",
            "website_url": "https://www.palantir.com",
        },
        {
            "region": "us",
            "name": "Canva",
            "source_type": "smartrecruiters",
            "external_key": "canva",
            "website_url": "https://www.canva.com",
        },
        {"region": "canada", "name": "D2L", "source_type": "greenhouse", "external_key": "d2l"},
        {"region": "canada", "name": "Ritual", "source_type": "greenhouse", "external_key": "ritual"},
        {"region": "canada", "name": "Miovision", "source_type": "applytojob", "external_key": "miovision"},
        {"region": "canada", "name": "Nulogy", "source_type": "applytojob", "external_key": "nulogy"},
        {"region": "quebec", "name": "SSENSE", "source_type": "smartrecruiters", "external_key": "ssense1"},
        {"region": "quebec", "name": "Averna", "source_type": "smartrecruiters", "external_key": "averna"},
        {"region": "us", "name": "Astronomer", "source_type": "ashby", "external_key": "astronomer"},
        {"region": "us", "name": "Anthropic", "source_type": "greenhouse", "external_key": "anthropic"},
        {"region": "us", "name": "Scale AI", "source_type": "greenhouse", "external_key": "scaleai"},
        {"region": "us", "name": "Databricks", "source_type": "greenhouse", "external_key": "databricks"},
        {"region": "us", "name": "Cloudflare", "source_type": "greenhouse", "external_key": "cloudflare"},
        {"region": "us", "name": "Twilio", "source_type": "greenhouse", "external_key": "twilio"},
        {"region": "us", "name": "Airtable", "source_type": "greenhouse", "external_key": "airtable"},
        {"region": "us", "name": "Gusto", "source_type": "greenhouse", "external_key": "gusto"},
        {"region": "us", "name": "Chime", "source_type": "greenhouse", "external_key": "chime"},
        {"region": "us", "name": "Mercury", "source_type": "greenhouse", "external_key": "mercury"},
        {"region": "us", "name": "Checkr", "source_type": "greenhouse", "external_key": "checkr"},
        {"region": "us", "name": "GitLab", "source_type": "greenhouse", "external_key": "gitlab"},
        {"region": "us", "name": "Okta", "source_type": "greenhouse", "external_key": "okta"},
        {"region": "us", "name": "MongoDB", "source_type": "greenhouse", "external_key": "mongodb"},
        {"region": "us", "name": "Elastic", "source_type": "greenhouse", "external_key": "elastic"},
        {"region": "us", "name": "PagerDuty", "source_type": "greenhouse", "external_key": "pagerduty"},
        {"region": "us", "name": "Qualtrics", "source_type": "greenhouse", "external_key": "qualtrics"},
        {"region": "us", "name": "Waymo", "source_type": "greenhouse", "external_key": "waymo"},
        {"region": "us", "name": "Faire", "source_type": "greenhouse", "external_key": "faire"},
        {"region": "us", "name": "Grammarly", "source_type": "greenhouse", "external_key": "grammarly"},
        {"region": "us", "name": "Amplitude", "source_type": "greenhouse", "external_key": "amplitude"},
        {"region": "us", "name": "Braze", "source_type": "greenhouse", "external_key": "braze"},
        {"region": "us", "name": "Carta", "source_type": "greenhouse", "external_key": "carta"},
        {"region": "us", "name": "CircleCI", "source_type": "greenhouse", "external_key": "circleci"},
        {"region": "us", "name": "Cockroach Labs", "source_type": "greenhouse", "external_key": "cockroachlabs"},
        {"region": "us", "name": "Netlify", "source_type": "greenhouse", "external_key": "netlify"},
        {"region": "us", "name": "PlanetScale", "source_type": "greenhouse", "external_key": "planetscale"},
        {"region": "us", "name": "LaunchDarkly", "source_type": "greenhouse", "external_key": "launchdarkly"},
        {"region": "us", "name": "Samsara", "source_type": "greenhouse", "external_key": "samsara"},
        {"region": "us", "name": "Block", "source_type": "greenhouse", "external_key": "block"},
        {"region": "us", "name": "Roblox", "source_type": "greenhouse", "external_key": "roblox"},
        {"region": "us", "name": "Postman", "source_type": "greenhouse", "external_key": "postman"},
        {"region": "us", "name": "Algolia", "source_type": "greenhouse", "external_key": "algolia"},
        {"region": "us", "name": "SoFi", "source_type": "greenhouse", "external_key": "sofi"},
        {"region": "us", "name": "Ginkgo Bioworks", "source_type": "greenhouse", "external_key": "ginkgobioworks"},
        {"region": "us", "name": "Fivetran", "source_type": "greenhouse", "external_key": "fivetran"},
        {"region": "us", "name": "ClickHouse", "source_type": "greenhouse", "external_key": "clickhouse"},
        {"region": "us", "name": "Anduril Industries", "source_type": "greenhouse", "external_key": "andurilindustries"},
        {"region": "dubai", "name": "BitOasis", "source_type": "smartrecruiters", "external_key": "bitoasis"},
        {"region": "dubai", "name": "Ziina", "source_type": "greenhouse", "external_key": "ziina"},
    )
    return tuple(_build_seed_record(**spec) for spec in specs)


def _catalog_companies(region: str, names: tuple[str, ...]) -> tuple[dict, ...]:
    return tuple(_build_seed_record(region=region, name=name) for name in names)


def _dedupe_records(*record_groups: tuple[dict, ...]) -> tuple[dict, ...]:
    seen_slugs: set[str] = set()
    records: list[dict] = []
    for group in record_groups:
        for record in group:
            slug = record["company"]["slug"]
            if slug in seen_slugs:
                continue
            seen_slugs.add(slug)
            records.append(record)
    return tuple(records)


_QUEBEC_CATALOG = (
    "Coveo",
    "Nuvei",
    "Hopper",
    "Dialogue",
    "nesto",
    "Plusgrade",
    "BrainBox AI",
    "Workleap",
    "Busbud",
    "Vention",
    "Plotly",
    "Vooban",
    "Valsoft",
    "Paper",
    "SSENSE",
    "Transit",
    "Botpress",
    "Intelcom",
    "MaintainX",
    "Behaviour Interactive",
    "mdf commerce",
    "LeddarTech",
    "Deep Sky",
    "Averna",
    "Flinks",
)

_CANADA_CATALOG = (
    "Shopify",
    "Clio",
    "Ada",
    "Jobber",
    "BenchSci",
    "KOHO",
    "1Password",
    "Clearco",
    "Float",
    "Neo Financial",
    "PointClickCare",
    "Hootsuite",
    "League",
    "Wattpad",
    "ApplyBoard",
    "Article",
    "Magnet Forensics",
    "Verafin",
    "StackAdapt",
    "Thinkific",
    "Unbounce",
    "Jane App",
    "FreshBooks",
    "Borrowell",
    "TouchBistro",
    "Benevity",
    "Geotab",
    "ecobee",
    "Mappedin",
    "Certn",
    "Rose Rocket",
    "Ritual",
    "Wealthica",
    "Symend",
    "Absorb Software",
    "Trulioo",
    "D2L",
    "Vidyard",
    "Axonify",
    "Miovision",
    "Nulogy",
)

_DUBAI_CATALOG = (
    "Kitopi",
    "Property Finder",
    "Bayut",
    "Dubizzle",
    "Dubizzle Group",
    "Noon",
    "Talabat",
    "Tabby",
    "Huspy",
    "CAFU",
    "Floward",
    "Fetchr",
    "Ziina",
    "Sarwa",
    "BitOasis",
    "eyewa",
    "NymCard",
    "Thndr",
    "Alaan",
    "Qlub",
    "Grubtech",
    "Astra Tech",
    "YAP",
    "Emirates NBD",
    "Mashreq",
    "e&",
    "du",
    "Swvl",
    "Pure Harvest Smart Farms",
)

_US_CATALOG = (
    "Anthropic",
    "Scale AI",
    "Rippling",
    "OpenPhone",
    "Anduril",
    "Palantir",
    "Snowflake",
    "Databricks",
    "Confluent",
    "Cloudflare",
    "Twilio",
    "Airtable",
    "Retool",
    "Benchling",
    "Zapier",
    "Gusto",
    "Chime",
    "Mercury",
    "Modern Treasury",
    "Checkr",
    "Snyk",
    "HashiCorp",
    "GitHub",
    "GitLab",
    "Okta",
    "MongoDB",
    "Elastic",
    "PagerDuty",
    "Box",
    "Qualtrics",
    "Cruise",
    "Waymo",
    "Rivian",
    "Faire",
    "Deel",
    "Oscar Health",
    "Grammarly",
    "Amplitude",
    "Braze",
    "Segment",
    "Carta",
    "CircleCI",
    "Cockroach Labs",
    "Netlify",
    "PlanetScale",
    "LaunchDarkly",
    "Sourcegraph",
    "Samsara",
    "Block",
    "Square",
    "Cash App",
    "Roblox",
    "OpenSea",
    "Patreon",
    "Loom",
    "Gumroad",
    "Postman",
    "Docker",
    "Supabase",
    "Algolia",
    "SoFi",
    "Circle",
    "Ginkgo Bioworks",
    "Recursion",
    "Tempus",
    "Adept AI",
    "Cerebras",
    "Lambda",
    "Weights & Biases",
    "Hex",
    "dbt Labs",
    "Fivetran",
    "ClickHouse",
    "Astronomer",
    "Coda",
    "Looker",
    "Miro",
    "Canva",
    "HubSpot",
    "OpenPhone",
    "Anduril Industries",
    "Airtable",
    "Mercury",
    "Anthropic",
    "Scale AI",
    "Rippling",
    "Runway",
    "Sierra",
    "Harvey",
    "Ramp",
    "Vanta",
    "Linear",
    "Perplexity",
    "Replit",
    "Render",
    "OpenAI",
    "Notion",
    "Plaid",
    "Stripe",
    "Figma",
    "Datadog",
    "Airbnb",
    "Reddit",
    "Coinbase",
    "Robinhood",
    "Brex",
    "Flexport",
    "Instacart",
    "Asana",
    "Dropbox",
    "Lyft",
    "Coursera",
    "Calendly",
    "Doximity",
    "Discord",
    "Vercel",
)

STARTER_COMPANIES = _dedupe_records(
    _supported_companies(),
    _catalog_companies("quebec", _QUEBEC_CATALOG),
    _catalog_companies("canada", _CANADA_CATALOG),
    _catalog_companies("us", _US_CATALOG),
    _catalog_companies("dubai", _DUBAI_CATALOG),
)

STARTER_JOBS = (
    {
        "id": "44444444-4444-4444-4444-444444444441",
        "company_slug": "openai",
        "source_type": "ashby",
        "source_job_key": "seed-openai-ml",
        "source_identity": "ashby:openai:seed-openai-ml",
        "title": "ML Engineer",
        "location_text": "Toronto, ON",
        "work_mode": "remote",
        "employment_type": "Full-time",
        "status": "active",
        "posted_at": datetime(2026, 3, 20, 12, 0, tzinfo=UTC),
        "apply_url": "https://openai.com/careers/ml-engineer",
        "description_text": "Seeded platform role for dashboard and apply flows.",
        "last_seen_at": datetime(2026, 3, 28, 12, 0, tzinfo=UTC),
        "missed_sync_count": 0,
    },
    {
        "id": "44444444-4444-4444-4444-444444444442",
        "company_slug": "vercel",
        "source_type": "greenhouse",
        "source_job_key": "seed-vercel-platform",
        "source_identity": "greenhouse:vercel:seed-vercel-platform",
        "title": "Platform Engineer",
        "location_text": "Remote",
        "work_mode": "remote",
        "employment_type": "Full-time",
        "status": "active",
        "posted_at": datetime(2026, 3, 21, 12, 0, tzinfo=UTC),
        "apply_url": "https://vercel.com/careers/platform-engineer",
        "description_text": "Seeded infrastructure role for summary and admin flows.",
        "last_seen_at": datetime(2026, 3, 28, 12, 0, tzinfo=UTC),
        "missed_sync_count": 0,
    },
)
